server:
  port: 8082
  servlet:
    context-path: /
spring:
  application:
    name: customer
  dubbo:
    registry:
     address: zookeeper://127.0.0.1:2181
#    consumer:
#      check: false
    protocol:
      name: dubbo
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: 0
      auto-offset-reset: earliest
      auto-commit-interval: 100
      properties:
        max:
          partition:
            fetch:
              bytes: 2097152
#    scan: com.dubboStudy.customer.controller
