server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: dubbo-spring-boot-provider
  dubbo:
    server: true
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
      status: server
  #  scan: com.dubboStudy.provider.serivce
